export const aiTaskTopology = [
  { id: "t1", technicalName: "aiTasks.header.container", name: "Task system header", scope: "AI Task System", description: "Identity and purpose of the reusable task workspace." },
  { id: "t1.1", technicalName: "aiTasks.header.title", name: "Task title", scope: "AI Task System", description: "Task title and execution status." },
  { id: "t1.2", technicalName: "aiTasks.header.actions", name: "Task actions", scope: "AI Task System", description: "Start agents, approve completion, and inspect details." },
  { id: "t2", technicalName: "aiTasks.sideCar.panel", name: "Task Side Car", scope: "AI Task System", description: "Collect requests, search tasks, and select persisted task plans." },
  { id: "t2.1", technicalName: "aiTasks.sideCar.list", name: "Task list", scope: "AI Task System", description: "List of persisted tasks with status and progress." },
  { id: "t2.2", technicalName: "aiTasks.sideCar.newTaskButton", name: "New task button", scope: "AI Task System", description: "Clear the selection and start a new task request." },
  { id: "t2.3", technicalName: "aiTasks.sideCar.searchInput", name: "Task search input", scope: "AI Task System", description: "Filter tasks by title, objective, or status." },
  { id: "t2.4", technicalName: "aiTasks.sideCar.statusFilter", name: "Task status filter", scope: "AI Task System", description: "Switch between active and completed tasks." },
  { id: "t3", technicalName: "aiTasks.workspace.canvas", name: "Task workspace canvas", scope: "AI Task System", description: "Show the selected task, refined prompt, acceptance criteria, assignments, progress, and agent evidence." },
  { id: "t3.1", technicalName: "aiTasks.workspace.welcomeState", name: "Task welcome state", scope: "AI Task System", description: "Explain task planning and offer starter prompts." },
  { id: "t4", technicalName: "aiTasks.composer.container", name: "Task prompt writer", scope: "AI Task System", description: "Bottom sticky prompt writer and controls to plan and refine agent work." },
  { id: "t4.1", technicalName: "aiTasks.composer.input", name: "Prompt input", scope: "AI Task System", description: "Prompt textarea to describe outcomes." },
  { id: "t4.2", technicalName: "aiTasks.composer.toolbar", name: "Prompt toolbar", scope: "AI Task System", description: "Prompt enhancement and contextual tools." },
  { id: "t4.2.1", technicalName: "aiTasks.composer.refineButton", name: "AI refinement button", scope: "AI Task System", description: "Prepare the request for AI refinement and planning." },
  { id: "t4.2.2", technicalName: "aiTasks.composer.attachButton", name: "Attach context button", scope: "AI Task System", description: "Attach supporting context to a task." },
  { id: "t4.2.3", technicalName: "aiTasks.composer.capabilitiesButton", name: "Capability requirements button", scope: "AI Task System", description: "Add capability requirements." },
  { id: "t4.2.4", technicalName: "aiTasks.composer.helpButton", name: "Task help button", scope: "AI Task System", description: "Open task writing guidance." },
  { id: "t4.3", technicalName: "aiTasks.composer.sendButton", name: "Send button", scope: "AI Task System", description: "Submit prompt to refine and plan." },
];
