import { useEffect, useState } from 'react';
import { Coffee, LayoutDashboard, CookingPot, Package, CalendarDays, ReceiptText, ExternalLink, RefreshCw } from 'lucide-react';
import { Button } from '@codexsun/ui/components/ui/button';
import { InterfaceTopologyDrawer, TopologyInspectionControl, TopologyMarker } from '@codexsun/devkit-ito';
import { useInterfaceTopologyOverlay } from '@codexsun/devkit-ito/use-interface-topology-overlay';
import { request, type Snapshot } from './api';
import { Dashboard } from './Dashboard';
import { Pos, Kitchen, Inventory, Bookings, field } from './Workspaces';
const pages = [{ name: 'Dashboard', icon: LayoutDashboard }, { name: 'POS', icon: ReceiptText }, { name: 'Kitchen', icon: CookingPot }, { name: 'Inventory', icon: Package }, { name: 'Bookings', icon: CalendarDays }];
const sections = [{ id: 'q1', name: 'Q Cafe navigation', scope: 'Q Cafe', description: 'App-owned restaurant workspaces.' }, { id: 'q2', name: 'Workspace header', scope: 'Q Cafe', description: 'Page title and primary action.' }, { id: 'q3', name: 'Active workspace', scope: 'Q Cafe', description: 'Dashboard, POS, kitchen, stock or reservations.' }];
export function App() {
  const [page, setPage] = useState(() => pages.find(page => `#${page.name}` === location.hash)?.name ?? 'Dashboard');
  const [token, setToken] = useState(() => sessionStorage.getItem('q-cafe-token') ?? '');
  const [data, setData] = useState<Snapshot>();
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const topology = useInterfaceTopologyOverlay(sections);
  function navigate(next: string) { location.hash = next; setPage(next); }
  async function refresh() { try { setData(await request<Snapshot>(token)); setError(''); } catch (error) { setError(String(error)); } }
  useEffect(() => { if (token) void refresh(); }, [token]);
  useEffect(() => { const handle = () => setPage(pages.find(page => `#${page.name}` === location.hash)?.name ?? 'Dashboard'); window.addEventListener('hashchange', handle); return () => window.removeEventListener('hashchange', handle); }, []);
  async function mutate(path: string, body: unknown) { setBusy(true); try { await request(token,path,body); await refresh(); return true; } catch (error) { setError(String(error)); return false; } finally { setBusy(false); } }
  if (!data) return <main className="grid min-h-screen place-items-center bg-background text-foreground"><form className="grid w-96 max-w-full gap-5 p-8" onSubmit={event => { event.preventDefault(); const value = String(new FormData(event.currentTarget).get('token')); sessionStorage.setItem('q-cafe-token', value); setToken(value); }}><Coffee size={36}/><h1 className="text-3xl font-semibold">Welcome to Q Cafe</h1><p className="text-muted-foreground">Enter your restaurant operator key to open the workspace.</p><input className={field} type="password" name="token" aria-label="Operator key" required /><Button className="cursor-pointer">Open workspace</Button>{error && <p role="alert">{error}</p>}</form></main>;
  const props = { data, busy, mutate };
  return <div className="min-h-screen bg-background text-foreground" {...topology.rootAttributes}><header className="flex h-20 items-center justify-between border-b border-border bg-card px-6 lg:px-9"><a href="#Dashboard" className="flex cursor-pointer items-center gap-3" onClick={() => navigate('Dashboard')}><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Coffee size={23}/></span><span className="text-xl font-semibold tracking-tight">Q Cafe<span className="ml-3 hidden text-xs font-normal uppercase tracking-widest text-muted-foreground sm:inline">Restaurant workspace</span></span></a><a className="flex cursor-pointer items-center gap-2 text-sm hover:text-primary" href={import.meta.env.VITE_CODEXSUN_URL ?? 'http://127.0.0.1:5173'} target="_blank" rel="noopener noreferrer">Codex OS <ExternalLink size={15}/></a></header>
    <div className="grid lg:grid-cols-[228px_1fr]"><aside className="ito-region border-b border-border bg-card p-5 lg:min-h-[calc(100vh-80px)] lg:border-r" {...topology.regionProps('q1')}><TopologyMarker id="q1" topology={topology}/><p className="px-3 pb-5 pt-3 text-xs font-semibold uppercase tracking-widest text-muted-foreground">Restaurant</p><nav className="flex flex-wrap gap-2 lg:flex-col">{pages.map(({name,icon: Icon}) => <button key={name} onClick={() => navigate(name)} aria-current={page === name ? 'page' : undefined} className={`flex cursor-pointer items-center gap-3 rounded-lg px-3 py-3 text-sm font-medium focus-visible:ring-2 focus-visible:ring-ring ${page === name ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'}`}><Icon size={19}/>{name}</button>)}</nav><div className="mt-10 space-y-4 border-t border-border px-3 pt-6"><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Connected workspaces</p>{[['Agents', import.meta.env.VITE_ZETRO_URL ?? 'http://127.0.0.1:5175'],['Chat', `${import.meta.env.VITE_CODEXSUN_URL ?? 'http://127.0.0.1:5173'}/?app=chat`]].map(([label,url]) => <a key={label} className="flex cursor-pointer items-center justify-between text-sm hover:text-primary" href={url} target="_blank" rel="noopener noreferrer">{label}<ExternalLink size={14}/></a>)}</div></aside>
    <main className="min-w-0 space-y-8 p-6 lg:px-10 lg:py-8"><div className="ito-region flex flex-wrap items-center justify-between gap-4" {...topology.regionProps('q2')}><TopologyMarker id="q2" topology={topology}/><div className="space-y-2"><p className="text-sm text-muted-foreground">{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}{data.demo ? ' · Demonstration workspace' : ''}</p><h1 className="text-3xl font-semibold tracking-tight">{page === 'Dashboard' ? 'Service overview' : page === 'POS' ? 'Point of sale' : page}</h1><p className="text-sm text-muted-foreground">{page === 'Dashboard' ? 'Everything you need for a smooth service.' : 'Q Cafe · Counter, kitchen and floor in sync.'}</p></div><div className="flex gap-3"><Button aria-label="Refresh workspace" title="Refresh workspace" variant="outline" className="cursor-pointer" onClick={() => void refresh()}><RefreshCw size={16}/></Button>{page !== 'POS' && <Button className="cursor-pointer" onClick={() => navigate('POS')}>+ New order</Button>}</div></div>
    {error && <p role="alert" className="rounded-lg border border-destructive p-4 text-destructive">{error}</p>}<div className="ito-region" {...topology.regionProps('q3')}><TopologyMarker id="q3" topology={topology}/>{page === 'Dashboard' && <Dashboard data={data} navigate={navigate}/>} {page === 'POS' && <Pos {...props}/>} {page === 'Kitchen' && <Kitchen {...props}/>} {page === 'Inventory' && <Inventory {...props}/>} {page === 'Bookings' && <Bookings {...props}/>}</div></main></div><TopologyInspectionControl topology={topology}/><InterfaceTopologyDrawer topology={topology}/></div>;
}

