import { Coffee, CookingPot, CalendarDays, Package } from 'lucide-react';
import { money, type Snapshot } from './api';
import type { InterfaceTopologyController } from '@codexsun/devkit-ito';
import { ItoRegion } from './ItoRegion';
export function Dashboard({ data, navigate, topology }: { data: Snapshot; navigate: (page: string) => void; topology: InterfaceTopologyController }) {
  const today = new Date().toLocaleDateString();
  const orders = data.orders.filter(order => new Date(order.created_at.replace(' ', 'T') + 'Z').toLocaleDateString() === today);
  const active = data.orders.filter(order => order.status !== 'served');
  const upcoming = data.bookings.filter(booking => new Date(booking.starts_at) > new Date());
  const low = data.inventory.filter(item => item.quantity < item.minimum);
  const stats = [ { label: 'Order value today', value: money(orders.reduce((sum, order) => sum + order.total, 0)), detail: `${orders.length} orders placed`, icon: Coffee }, { label: 'In the kitchen', value: active.length, detail: 'Tickets awaiting service', icon: CookingPot }, { label: 'Upcoming bookings', value: upcoming.length, detail: 'Confirmed reservations', icon: CalendarDays }, { label: 'Stock attention', value: low.length, detail: 'Items below reorder level', icon: Package } ];
  return <ItoRegion id="q6" topology={topology} className="space-y-8"><ItoRegion id="q6.1" topology={topology} className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, detail, icon: Icon }) => <article key={label} className="space-y-4 border-b border-border pb-6"><div className="flex items-center justify-between text-sm text-muted-foreground">{label}<Icon size={18} /></div><p className="text-3xl font-semibold tracking-tight">{value}</p><p className="text-sm text-muted-foreground">{detail}</p></article>)}</ItoRegion>
    <div className="grid gap-8 xl:grid-cols-[1.6fr_1fr]"><ItoRegion id="q6.2" topology={topology} tag="section" className="space-y-5 rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">The floor, at a glance</h2><span className="text-sm text-muted-foreground">12 tables</span></div><ItoRegion id="q6.2.1" topology={topology} className="grid grid-cols-3 gap-3 sm:grid-cols-4">{Array.from({ length: 12 }, (_, index) => { const name = `T${String(index + 1).padStart(2, '0')}`; const occupied = active.some(order => order.table_name === name); return <button onClick={() => navigate('POS')} key={name} className={`flex cursor-pointer flex-col items-center gap-2 rounded-xl border p-5 focus-visible:ring-2 focus-visible:ring-ring ${occupied ? 'border-primary bg-primary/10 text-foreground' : 'border-border bg-muted/30 hover:bg-accent hover:text-accent-foreground'}`}><Coffee size={22} /><span className="font-semibold">{name}</span><span className="text-xs">{occupied ? 'Open order' : 'Available'}</span></button>; })}</ItoRegion><p className="text-sm text-muted-foreground">Floor status is based on open kitchen orders.</p></ItoRegion>
    <section className="space-y-5"><ItoRegion id="q6.3" topology={topology} className="space-y-4 rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">Needs your attention</h2>{low.map(item => <div key={item.id} className="flex justify-between text-sm"><span>{item.name}</span><span>{item.quantity} {item.unit} left</span></div>)}{!low.length && <p className="text-sm text-muted-foreground">Stock levels are above their reorder points.</p>}<button className="cursor-pointer text-sm font-medium underline underline-offset-4" onClick={() => navigate('Inventory')}>Review inventory</button></ItoRegion></section></div>
    <div className="grid gap-8 xl:grid-cols-2"><ItoRegion id="q6.4" topology={topology} tag="section" className="space-y-4"><h2 className="text-lg font-semibold">Recent orders</h2><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-muted-foreground"><tr>{['Order','Table / service','Kitchen status','Value'].map(title => <th className="py-3 font-medium" key={title}>{title}</th>)}</tr></thead><tbody>{[...data.orders].reverse().slice(0, 5).map(order => <tr key={order.id} className="border-b border-border"><td className="py-4">#{String(order.id).padStart(3,'0')}</td><td>{order.table_name}</td><td className="capitalize">{order.status}</td><td>{money(order.total)}</td></tr>)}</tbody></table>{!data.orders.length && <p className="py-8 text-sm text-muted-foreground">No orders yet. Start your first order at the counter.</p>}</div></ItoRegion><ItoRegion id="q6.5" topology={topology} tag="section" className="space-y-4"><h2 className="text-lg font-semibold">Activity</h2><div className="divide-y divide-border rounded-2xl border border-border bg-card">{[...data.activities].reverse().slice(0, 5).map(activity => <article className="px-4 py-3 text-sm" key={activity.id}><p>{activity.detail}</p><time className="text-xs text-muted-foreground">{new Date(`${activity.created_at}Z`).toLocaleString()}</time></article>)}{!data.activities.length && <p className="p-4 text-sm text-muted-foreground">Activity will appear as the team uses Q Cafe.</p>}</div></ItoRegion></div>
  </ItoRegion>;
}
