import type { InterfaceTopologySection } from '@codexsun/devkit-ito';

const item = (id: string, technicalName: string, name: string, scope: string, description: string): InterfaceTopologySection => ({ id, technicalName, name, scope, description });

export const qCafeTopology: InterfaceTopologySection[] = [
  item('q1', 'qCafe.authentication.loginForm', 'Cashier login', 'Authentication', 'Open Q Cafe with a four-digit cashier PIN.'),
  item('q1.1', 'qCafe.authentication.pinInput', 'Cashier PIN input', 'Authentication', 'Enter the cashier PIN.'),
  item('q1.2', 'qCafe.authentication.submitButton', 'Open workspace button', 'Authentication', 'Validate the PIN and open the restaurant desk.'),
  item('q1.3', 'qCafe.authentication.errorAlert', 'Login error', 'Authentication', 'Show an authentication failure.'),
  item('q2', 'qCafe.commandBar.container', 'Command bar', 'Application chrome', 'Q Cafe identity and utility controls.'),
  item('q2.1', 'qCafe.commandBar.navigationToggle', 'Navigation toggle', 'Command bar', 'Collapse or expand restaurant navigation.'),
  item('q2.2', 'qCafe.commandBar.homeLink', 'Q Cafe home link', 'Command bar', 'Return to the service dashboard.'),
  item('q2.3', 'qCafe.commandBar.searchButton', 'Global search button', 'Command bar', 'Open global search.'),
  item('q2.4', 'qCafe.commandBar.notificationsButton', 'Notifications button', 'Command bar', 'Open restaurant notifications.'),
  item('q2.5', 'qCafe.commandBar.accountBadge', 'Cashier account badge', 'Command bar', 'Identify the active cashier session.'),
  item('q3', 'qCafe.sideCar.panel', 'Q Cafe side car', 'Workspace navigation', 'Navigate restaurant workspaces and connected tools.'),
  item('q3.1', 'qCafe.sideCar.navigationList', 'Restaurant navigation', 'Workspace navigation', 'Select Dashboard, POS, Kitchen, Inventory, or Bookings.'),
  item('q3.1.1', 'qCafe.sideCar.dashboardButton', 'Dashboard button', 'Workspace navigation', 'Open the service dashboard.'),
  item('q3.1.2', 'qCafe.sideCar.posButton', 'POS button', 'Workspace navigation', 'Open point of sale.'),
  item('q3.1.3', 'qCafe.sideCar.kitchenButton', 'Kitchen button', 'Workspace navigation', 'Open kitchen tickets.'),
  item('q3.1.4', 'qCafe.sideCar.inventoryButton', 'Inventory button', 'Workspace navigation', 'Open stock management.'),
  item('q3.1.5', 'qCafe.sideCar.bookingsButton', 'Bookings button', 'Workspace navigation', 'Open reservations.'),
  item('q3.1.6', 'qCafe.sideCar.settingsButton', 'Settings button', 'Workspace navigation', 'Open restaurant settings.'),
  item('q3.3', 'qCafe.sideCar.railToggle', 'Side car rail toggle', 'Workspace navigation', 'Collapse or expand the Q Cafe side car.'),
  item('q4', 'qCafe.workspace.header', 'Workspace header', 'Active workspace', 'Show the page title and primary actions.'),
  item('q4.1', 'qCafe.workspace.refreshButton', 'Refresh workspace button', 'Active workspace', 'Reload the current restaurant snapshot.'),
  item('q4.2', 'qCafe.workspace.newOrderButton', 'New order button', 'Active workspace', 'Open point of sale for a new order.'),
  item('q4.3', 'qCafe.workspace.errorAlert', 'Workspace error', 'Active workspace', 'Show an actionable data or operation error.'),
  item('q5', 'qCafe.workspace.canvas', 'Active workspace canvas', 'Active workspace', 'Host the selected Q Cafe page.'),
  item('q6', 'qCafe.dashboard.container', 'Dashboard', 'Dashboard', 'Summarize service, tables, stock, orders, and activity.'),
  item('q6.1', 'qCafe.dashboard.metricCards', 'Service metric cards', 'Dashboard', 'Show order value, kitchen, booking, and stock totals.'),
  item('q6.2', 'qCafe.dashboard.floorPanel', 'Floor status panel', 'Dashboard', 'Show current table availability.'),
  item('q6.2.1', 'qCafe.dashboard.tableButtons', 'Table buttons', 'Dashboard', 'Open an order from a table.'),
  item('q6.3', 'qCafe.dashboard.stockAttention', 'Stock attention panel', 'Dashboard', 'Show low-stock items and open Inventory.'),
  item('q6.4', 'qCafe.dashboard.recentOrders', 'Recent orders table', 'Dashboard', 'Show the latest restaurant orders.'),
  item('q6.5', 'qCafe.dashboard.activityFeed', 'Activity feed', 'Dashboard', 'Show recent restaurant activity.'),
  item('q7', 'qCafe.pos.billingDesk', 'POS billing desk', 'POS', 'Create a bill through keyboard-first cashier entry.'),
  item('q7.1', 'qCafe.pos.billPanel', 'POS bill', 'POS', 'Show table, bill lines, tax, and bill actions.'),
  item('q7.1.1', 'qCafe.pos.tableSelect', 'Table selector', 'POS', 'Choose a serving table or takeaway service.'),
  item('q7.1.2', 'qCafe.pos.billItems', 'POS items table', 'POS', 'Show table, chair, item, quantity, rate, and amount columns.'),
  item('q7.1.2.1', 'qCafe.pos.billItem', 'POS item', 'POS', 'Show a single entered POS item.'),
  item('q7.1.2.2', 'qCafe.pos.removeItemButton', 'Remove POS item button', 'POS', 'Remove an entered POS item.'),
  item('q7.1.3', 'qCafe.pos.lineEntry', 'Line entry controls', 'POS', 'Enter item code, name, quantity, and rate.'),
  item('q7.1.3.1', 'qCafe.pos.itemCodeInput', 'Item code input', 'POS', 'Enter or look up an item code.'),
  item('q7.1.3.2', 'qCafe.pos.itemNameInput', 'Item name input', 'POS', 'Enter or look up an item name.'),
  item('q7.1.3.3', 'qCafe.pos.quantityInput', 'Quantity input', 'POS', 'Enter the line quantity.'),
  item('q7.1.3.4', 'qCafe.pos.rateInput', 'Rate input', 'POS', 'Enter or override the unit rate.'),
  item('q7.1.3.5', 'qCafe.pos.lineAmount', 'Line amount', 'POS', 'Show the calculated line amount.'),
  item('q7.1.4', 'qCafe.pos.addLineButton', 'Add line button', 'POS', 'Add the entered item to the order.'),
  item('q7.1.5', 'qCafe.pos.billTotals', 'Bill totals', 'POS', 'Show taxable, GST, grand total, print, and save actions.'),
  item('q7.1.5.1', 'qCafe.pos.printBillButton', 'Print bill button', 'POS', 'Print the current order bill.'),
  item('q7.1.5.2', 'qCafe.pos.saveBillButton', 'Save bill button', 'POS', 'Persist the POS bill.'),
  item('q7.1.6', 'qCafe.pos.paymentPanel', 'Payment details', 'POS', 'Record full, partial, or split payments against the saved bill.'),
  item('q7.2', 'qCafe.pos.menuPanel', 'Menu item panel', 'POS', 'Select an item from the restaurant menu.'),
  item('q7.2.1', 'qCafe.pos.menuList', 'Menu item list', 'POS', 'Browse available restaurant menu items.'),
  item('q7.2.2', 'qCafe.pos.menuItemButton', 'Menu item button', 'POS', 'Select a menu item for the cashier entry row.'),
  item('q8', 'qCafe.kitchen.board', 'Kitchen board', 'Kitchen', 'Group tickets by queued, preparing, and ready status.'),
  item('q8.1', 'qCafe.kitchen.statusColumns', 'Kitchen status columns', 'Kitchen', 'Show tickets in each preparation stage.'),
  item('q8.2', 'qCafe.kitchen.advanceButtons', 'Advance ticket buttons', 'Kitchen', 'Move an order to its next kitchen status.'),
  item('q9', 'qCafe.inventory.container', 'Inventory workspace', 'Inventory', 'Review stock and record adjustments.'),
  item('q9.1', 'qCafe.inventory.adjustmentForms', 'Stock adjustment forms', 'Inventory', 'Enter quantity changes and reasons.'),
  item('q9.2', 'qCafe.inventory.saveButtons', 'Save adjustment buttons', 'Inventory', 'Persist stock adjustments.'),
  item('q10', 'qCafe.bookings.container', 'Bookings workspace', 'Bookings', 'Review reservations and reserve tables.'),
  item('q10.1', 'qCafe.bookings.reservationList', 'Reservation list', 'Bookings', 'Show existing reservations.'),
  item('q10.2', 'qCafe.bookings.bookingForm', 'Booking form', 'Bookings', 'Enter guest, party, table, and arrival details.'),
  item('q10.3', 'qCafe.bookings.confirmButton', 'Confirm booking button', 'Bookings', 'Save the reservation.'),
  item('q11', 'qCafe.settings.container', 'Settings workspace', 'Settings', 'Configure restaurant profile, POS billing options, appearance, and system preferences.'),
  item('q11.1', 'qCafe.settings.tabs', 'Settings navigation tabs', 'Settings', 'Switch between General, POS & Tax, Appearance, and System settings.'),
  item('q11.2', 'qCafe.settings.form', 'Settings configuration form', 'Settings', 'Edit restaurant configuration options and preferences.'),
  item('q11.3', 'qCafe.settings.saveButton', 'Save settings button', 'Settings', 'Persist updated settings locally.'),
];
