import type { InterfaceTopologySection } from "@codexsun/devkit-ito";

export const coreTopology: InterfaceTopologySection[] = [
  { id: "01", technicalName: "overview.commandBar.container", name: "Command bar", scope: "Application chrome", description: "Workspace commands and the complete top-level utility surface." },
  { id: "1.1", technicalName: "overview.commandBar.sideCarToggle", name: "Side car toggle", scope: "Command bar", description: "Inspect Toggle workspace navigation in Command bar." },
  { id: "02", technicalName: "overview.branding.homeLink", name: "Home branding link", scope: "Command bar", description: "Home navigation through the product logo and name." },
  { id: "03", technicalName: "overview.search.triggerButton", name: "Global search button", scope: "Command bar", description: "Search trigger and Ctrl + K command dialog." },
  { id: "3.1", technicalName: "overview.search.inputAndCloseGroup", name: "Search input and close controls", scope: "Search popup", description: "Inspect Search input and close control in Search popup." },
  { id: "3.2", technicalName: "overview.search.homeCommand", name: "Go to Home", scope: "Search popup", description: "Inspect Go to Home in Search popup." },
  { id: "3.3", technicalName: "overview.search.applicationsCommand", name: "Open Applications", scope: "Search popup", description: "Inspect Open Applications in Search popup." },
  { id: "3.4", technicalName: "overview.search.notificationsCommand", name: "Open Notifications", scope: "Search popup", description: "Inspect Open Notifications in Search popup." },
  { id: "3.5", technicalName: "overview.search.userMenuCommand", name: "Open User Menu", scope: "Search popup", description: "Inspect Open User Menu in Search popup." },
  { id: "04", technicalName: "overview.notifications.triggerButton", name: "Notifications button", scope: "Command bar", description: "Notification state, unread indicator, and notification menu." },
  { id: "4.1", technicalName: "overview.notifications.inbox", name: "Notification inbox", scope: "Notifications popup", description: "Inspect Notification inbox in Notifications popup." },
  { id: "05", technicalName: "overview.applicationLauncher.triggerButton", name: "Application launcher button", scope: "Command bar", description: "Application switcher and launcher menu." },
  { id: "5.1", technicalName: "overview.applicationLauncher.coreItem", name: "Core application", scope: "Application launcher", description: "Inspect Core application in Application launcher." },
  { id: "5.2", technicalName: "overview.applicationLauncher.devkitItem", name: "DevKit application", scope: "Application launcher", description: "Inspect DevKit application in Application launcher." },
  { id: "5.3", technicalName: "overview.applicationLauncher.agentCrewItem", name: "Agent Crew application", scope: "Application launcher", description: "Inspect Agent Crew application in Application launcher." },
  { id: "06", technicalName: "overview.userMenu.triggerButton", name: "User menu button", scope: "Command bar", description: "Account identity and user actions." },
  { id: "6.1", technicalName: "overview.userMenu.profileItem", name: "Manage profile item", scope: "User menu", description: "Inspect Manage profile in User menu." },
  { id: "6.2", technicalName: "overview.userMenu.appearanceSubmenu", name: "Appearance submenu", scope: "User menu", description: "Inspect Appearance submenu in User menu." },
  { id: "6.2.1", technicalName: "overview.appearance.systemThemeItem", name: "System theme", scope: "Appearance submenu", description: "Inspect System theme in Appearance submenu." },
  { id: "6.2.2", technicalName: "overview.appearance.lightThemeItem", name: "Light theme", scope: "Appearance submenu", description: "Inspect Light theme in Appearance submenu." },
  { id: "6.2.3", technicalName: "overview.appearance.darkThemeItem", name: "Dark theme", scope: "Appearance submenu", description: "Inspect Dark theme in Appearance submenu." },
  { id: "6.3", technicalName: "overview.userMenu.signOutItem", name: "Sign out item", scope: "User menu", description: "Inspect Sign out in User menu." },
  { id: "07", technicalName: "overview.primaryDock.container", name: "Primary navigation dock", scope: "Primary navigation", description: "Platform Overview first, followed by Chat and Zetro, plus bottom-aligned utility actions." },
  { id: "7.1", technicalName: "overview.primaryDock.overviewButton", name: "Overview", scope: "Primary dock", description: "Inspect Overview in Primary dock." },
  { id: "7.2", technicalName: "overview.primaryDock.chatButton", name: "Chat", scope: "Primary dock", description: "Inspect Chat in Primary dock." },
  { id: "7.3", technicalName: "overview.primaryDock.zetroButton", name: "Zetro", scope: "Primary dock", description: "Inspect Zetro in Primary dock." },
  { id: "7.4", technicalName: "overview.primaryDock.docsButton", name: "Docs", scope: "Primary dock", description: "Inspect Docs in Primary dock." },
  { id: "7.5", technicalName: "overview.primaryDock.linksButton", name: "Links", scope: "Primary dock", description: "Inspect Links in Primary dock." },
  { id: "7.6", technicalName: "overview.primaryDock.settingsButton", name: "Settings", scope: "Primary dock", description: "Inspect Settings in Primary dock." },
  { id: "08", technicalName: "overview.workspace.canvas", name: "Workspace canvas", scope: "Main workspace", description: "Primary MDI content and active feature workspace." },
  { id: "09", technicalName: "overview.contextDock.container", name: "Context navigation dock", scope: "Context navigation", description: "Right-side properties, history, topology, and notification actions." },
  { id: "9.1", technicalName: "overview.contextDock.propertiesButton", name: "Properties", scope: "Context dock", description: "Inspect Properties in Context dock." },
  { id: "9.2", technicalName: "overview.contextDock.historyButton", name: "Activity history", scope: "Context dock", description: "Inspect Activity history in Context dock." },
  { id: "9.3", technicalName: "overview.contextDock.notificationsButton", name: "Notifications", scope: "Context dock", description: "Inspect Notifications in Context dock." },
  { id: "10", technicalName: "overview.contextDock.topologyButton", name: "Topology inspection button", scope: "Context dock", description: "Shows or hides interface labels and opens topology inspection." },
  { id: "11", technicalName: "overview.sideCar.panel", name: "Overview side car", scope: "Workspace canvas", description: "Generic application-owned companion content hosted beside the active workspace." },
  { id: "11.1", technicalName: "overview.sideCar.content", name: "Side car content", scope: "Overview sidebar", description: "Platform navigation inside the companion panel." },
  { id: "11.1.1", technicalName: "overview.sideCar.navigationGroup", name: "CODEXSUN OS navigation group", scope: "Overview sidebar", description: "Inspect CODEXSUN OS navigation group in Overview sidebar." },
  { id: "11.1.1.1", technicalName: "overview.sideCar.overviewLink", name: "Overview navigation item", scope: "Overview sidebar", description: "Inspect Overview navigation item in Overview sidebar." },
  { id: "12", technicalName: "overview.sideCar.railToggle", name: "Side car rail toggle", scope: "Workspace canvas", description: "Rail that collapses or expands the application side car." },
  { id: "13", technicalName: "overview.workspace.surface", name: "Workspace surface", scope: "Workspace canvas", description: "Inset surface beside the application sidebar for active MDI content." },
  { id: "14", technicalName: "overview.workspace.content", name: "Workspace content", scope: "Workspace surface", description: "Scrollable active-content area that loads the selected workspace item." },
  { id: "15", technicalName: "overview.welcome.container", name: "Overview welcome", scope: "Platform", description: "Platform-owned welcome page shown first when CODEXSUN OS opens." },
  { id: "15.1", technicalName: "overview.welcome.headingBlock", name: "Welcome heading", scope: "Overview", description: "Inspect Welcome heading in Overview." },
  { id: "15.2", technicalName: "overview.welcome.gettingStartedBlock", name: "Start from your desk", scope: "Overview", description: "Inspect Start from your desk in Overview." },
  { id: "15.3", technicalName: "overview.welcome.ownershipBlock", name: "Platform ownership", scope: "Overview", description: "Inspect Platform ownership in Overview." },
];
