[package]
name = "q-cafe-desktop"
version = "0.1.7"
description = "Q Cafe Windows desktop application"
authors = ["CODEXSUN"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.10.3", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
