import type { InterfaceTopologySection } from "@codexsun/devkit-ito";

export const chatTopology: InterfaceTopologySection[] = [
  { id: "c1", technicalName: "chat.workspace.container", name: "Chat workspace", scope: "Chat", description: "Authenticated DevKit direct conversations." },
  { id: "c1.1", technicalName: "chat.workspace.welcomeState", name: "Conversation welcome", scope: "Chat", description: "Choose a conversation to begin." },
  { id: "c1.2", technicalName: "chat.workspace.errorAlert", name: "Chat error", scope: "Chat", description: "Connection or message error feedback." },
  { id: "c2", technicalName: "chat.sideCar.panel", name: "Chat side car", scope: "Chat", description: "Conversation navigation beside the chat." },
  { id: "c2.1", technicalName: "chat.sideCar.content", name: "Side car content", scope: "Chat", description: "Chat-owned companion content." },
  { id: "c2.1.1", technicalName: "chat.sideCar.conversationNavigation", name: "Chat side car", scope: "Chat", description: "WhatsApp-style recent conversations and contact history." },
  { id: "c2.1.1.1", technicalName: "chat.sideCar.newConversationButton", name: "New chat", scope: "Chat", description: "Open the contact picker to start a conversation." },
  { id: "c2.1.1.2", technicalName: "chat.sideCar.searchInput", name: "Chat search", scope: "Chat", description: "Filter contact names and message previews." },
  { id: "c2.1.1.3", technicalName: "chat.sideCar.archiveFilter", name: "Chat history filter", scope: "Chat", description: "Switch between recent and archived chat history." },
  { id: "c2.1.1.4", technicalName: "chat.sideCar.conversationList", name: "Recent chat list", scope: "Chat", description: "Newest-first contacts with avatar, preview, time, and unread messages." },
  { id: "c2.2", technicalName: "chat.sideCar.railToggle", name: "Side car rail toggle", scope: "Chat", description: "Collapse or expand the companion panel." },
  { id: "c3", technicalName: "chat.header.container", name: "Chat header", scope: "Chat", description: "Active conversation identity, presence, and actions." },
  { id: "c3.1", technicalName: "chat.header.identity", name: "Conversation identity", scope: "Chat", description: "Contact avatar, display name, and presence." },
  { id: "c3.1.1", technicalName: "chat.header.avatar", name: "Contact avatar", scope: "Chat", description: "Initials avatar and online indicator." },
  { id: "c3.1.2", technicalName: "chat.header.presence", name: "Contact presence", scope: "Chat", description: "Active contact name and online status." },
  { id: "c3.2", technicalName: "chat.header.actions", name: "Conversation actions", scope: "Chat", description: "Video, audio, and overflow controls for the active chat." },
  { id: "c3.2.1", technicalName: "chat.header.videoCallButton", name: "Video call", scope: "Chat", description: "Start a video call when the connected provider supports it." },
  { id: "c3.2.2", technicalName: "chat.header.audioCallButton", name: "Audio call", scope: "Chat", description: "Start an audio call when the connected provider supports it." },
  { id: "c3.2.3", technicalName: "chat.header.overflowMenu", name: "Conversation options", scope: "Chat", description: "Open the archive and deletion actions." },
  { id: "c3.2.3.1", technicalName: "chat.header.overflowMenu.archiveAction", name: "Archive this chat", scope: "Chat", description: "Archive or restore the active chat through the DevKit preference contract." },
  { id: "c3.2.3.2", technicalName: "chat.header.overflowMenu.deleteAction", name: "Delete this chat", scope: "Chat", description: "Delete action reserved until the DevKit public contract provides permanent deletion." },
  { id: "c3.2.4", technicalName: "chat.header.detailsButton", name: "Conversation details", scope: "Chat", description: "Open details for the active conversation." },
  { id: "c4", technicalName: "chat.connection.form", name: "DevKit connection form", scope: "Chat", description: "Account connection form." },
  { id: "c4.1", technicalName: "chat.connection.apiUrlInput", name: "API URL input", scope: "Chat", description: "Set the DevKit server." },
  { id: "c4.2", technicalName: "chat.connection.accessTokenInput", name: "Access token input", scope: "Chat", description: "Session-only authentication." },
  { id: "c4.3", technicalName: "chat.connection.connectButton", name: "Connect DevKit button", scope: "Chat", description: "Connect to DevKit." },
  { id: "c5", technicalName: "chat.contacts.picker", name: "Contact picker", scope: "Chat", description: "Choose a contact to start a direct conversation." },
  { id: "c7", technicalName: "chat.history.container", name: "Message history", scope: "Chat", description: "Paged messages, timestamps, delivery state, and copy actions." },
  { id: "c7.1", technicalName: "chat.history.loadOlderButton", name: "Load older messages", scope: "Chat", description: "Fetch the previous history page." },
  { id: "c7.2", technicalName: "chat.history.transcript", name: "Message transcript", scope: "Chat", description: "Loaded messages, date separators, delivery details, and copy actions." },
  { id: "c8", technicalName: "chat.composer.container", name: "Message composer", scope: "Chat", description: "Draft and send a private message." },
  { id: "c8.1", technicalName: "chat.composer.messageInput", name: "Message input", scope: "Chat", description: "Write a private message." },
  { id: "c8.2", technicalName: "chat.composer.toolbar", name: "Composer toolbar", scope: "Chat", description: "Attachment, mention, command, topic, and help controls." },
  { id: "c8.2.1", technicalName: "chat.composer.attachButton", name: "Attach a file", scope: "Chat", description: "Inspect the composer control." },
  { id: "c8.2.2", technicalName: "chat.composer.mentionButton", name: "Mention someone", scope: "Chat", description: "Inspect the composer control." },
  { id: "c8.2.3", technicalName: "chat.composer.commandsButton", name: "Commands", scope: "Chat", description: "Inspect the composer control." },
  { id: "c8.2.4", technicalName: "chat.composer.topicButton", name: "Add topic", scope: "Chat", description: "Inspect the composer control." },
  { id: "c8.2.5", technicalName: "chat.composer.helpButton", name: "Composer help", scope: "Chat", description: "Inspect the composer control." },
  { id: "c8.3", technicalName: "chat.composer.sendButton", name: "Send message", scope: "Chat", description: "Submit the private message." },
];
